name: go test
on:
  push:
    branches:
    - main
    tags-ignore:
    - "*.*.*"
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        go: ["1.15"]
        os: [ubuntu-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/setup-go@master
      with:
        go-version: ${{ matrix.go }}
    - uses: actions/checkout@master
    - name: go test
      run: "AT=true go test -v -race -coverprofile=coverage.txt -covermode=atomic ./..."
    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.txt
