name: go test
on:
  push:
    tags-ignore:
    - "*.*.*"
    branches:
    - master
    - main
  pull_request:
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        go: ["1.18"]
        os: [ubuntu-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}
    - uses: actions/checkout@v3
    - name: go test
      run: "AT=true go test -v -race -coverprofile=coverage.txt -covermode=atomic ./..."
